"""File storage helpers."""

from __future__ import annotations

import secrets
from pathlib import Path

from fastapi import UploadFile

from app.core.settings import get_settings


async def save_upload_file(upload: UploadFile, *, namespace: str) -> tuple[bytes, str, str]:
    settings = get_settings()
    upload_dir = Path(settings.upload_dir) / namespace
    upload_dir.mkdir(parents=True, exist_ok=True)

    raw_bytes = await upload.read()
    suffix = Path(upload.filename or "upload.bin").suffix
    stored_filename = f"{secrets.token_hex(16)}{suffix}"
    destination = upload_dir / stored_filename
    destination.write_bytes(raw_bytes)

    return raw_bytes, stored_filename, str(destination)


def save_binary_payload(
    *,
    payload: bytes,
    namespace: str,
    suffix: str,
) -> tuple[str, str]:
    """Persist raw bytes generated by providers and return filename and path."""

    settings = get_settings()
    upload_dir = Path(settings.upload_dir) / namespace
    upload_dir.mkdir(parents=True, exist_ok=True)

    stored_filename = f"{secrets.token_hex(16)}{suffix}"
    destination = upload_dir / stored_filename
    destination.write_bytes(payload)
    return stored_filename, str(destination)
